# .scrutinizer.yml

filter:
    excluded_paths:
        - 'tests/*'
        - 'contrib/*'
        - 'docs*/*'
checks:
    php: true
    
coding_style:
    php:
        spaces:
            around_operators:
                multiplicative: false
            other:
                after_type_cast: false
build:
    environment:
        php: '7.1'
        
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - 'php vendor/bin/codecept run'
                    - 'php-scrutinizer-run'
                    -
                        command: phpcs-run
                        use_website_config: true